language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements_dev.txt
  - python setup.py install
script:
  - pytest tests/ --cov=./
after_success:
  - git config --global user.name "semantic-release (via TravisCI)"
  - git config --global user.email "semantic-release@travis"
  - pip install python-semantic-release
  - semantic-release publish
  - codecov --token=86e102c8-b101-4148-b38a-7d67fa9870ca